version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "6066:80"
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/symfony.conf:/etc/nginx/conf.d/symfony.conf:ro

  php:
    build: ""
    volumes:
      - ./:/app
    working_dir: /app